### PR TITLE
Merge to master; Switch to options mapping using Serialize

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/hongkai-dai/drake/33)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
@jwnimmer-tri this PR contains a lot of changes in meshcat, do you intend to include these changes?

> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/drake/33#-:-NkS6buz89SKk07Ws-hS:b-lrfyz3)* status: 0 of 12 files reviewed, all discussions resolved

**Comment by jwnimmer-tri** [comment]
That's just the merge to master.  If you like, you can rebase your PR and then cherry-pick just the last commit from here.

**Review by hongkai-dai — CHANGES_REQUESTED** [review]
:lgtm: 

> Reviewed 7 of 12 files at r4.
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/drake/33#-:-NkSPBV96gS1sYploeGC:bg7igkv)* status: 7 of 14 files reviewed, 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`solvers/clarabel_solver.cc` line 219 at r4](https://reviewable.io/reviews/hongkai-dai/drake/33#-NkS9lAOBU5i3MZ52sKY:-NkS9lAOBU5i3MZ52sKZ:bab0zvo) ([raw file](https://github.com/hongkai-dai/drake/blob/a0e69d10d16daa04ac068c71e8fc6b27d0b6c1f4/solvers/clarabel_solver.cc#L219)):*
> ```cpp
>  private:
>   template <typename T>
>   void SetFromDoubleMap(const char* name, T* clarabel_value) {
> ```

Why template this `T`? I would think we always have `T=double`?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/drake/33)* status: 7 of 14 files reviewed, 1 unresolved discussion (waiting on @hongkai-dai)

___
*[`solvers/clarabel_solver.cc` line 219 at r4](https://reviewable.io/reviews/hongkai-dai/drake/33#-NkS9lAOBU5i3MZ52sKY:-NkSWS-Y2kqpcDvCIq5W:b-j78366) ([raw file](https://github.com/hongkai-dai/drake/blob/a0e69d10d16daa04ac068c71e8fc6b27d0b6c1f4/solvers/clarabel_solver.cc#L219)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Why template this `T`? I would think we always have `T=double`?
</blockquote></details>

You're right -- at the moment, none of clarabel's settings are `float`, so we can replace `T` with `double` here.  Can you take of that when you pull this into the main PR?

**Review by hongkai-dai — COMMENTED** [review]
I cherry-picked the last commit to the `clarabel_options` branch.

> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/drake/33#-:-NkSb2VLEmmVwW1OANjz:bu1zaax)* status: 7 of 14 files reviewed, 1 unresolved discussion

**Pull request closed without merging**
