### PR TITLE
Add point in set return variables

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
For https://github.com/RobotLocomotion/drake/pull/19634

- - -
This change is [Reviewable](https://reviewable.io/reviews/hongkai-dai/drake/31)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/drake/31)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`geometry/optimization/cartesian_product.cc` line 202 at r1](https://reviewable.io/reviews/hongkai-dai/drake/31#-NYUD9GP8mNFLySKXRLy:-NYUD9GP8mNFLySKXRLz:ban2q34) ([raw file](https://github.com/hongkai-dai/drake/blob/a7869fefd9e1726b8052a88347d0a5a64cd80544/geometry/optimization/cartesian_product.cc#L202)):*
> ```cpp
>   VectorX<Variable> new_vars_vec =
>       Eigen::Map<VectorX<Variable>>(new_vars.data(), new_vars.size());
>   return {std::move(new_vars_vec), std::move(new_constraints)};
> ```

BTW, For my own education, would return-value-optimization automatically move these?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/drake/31)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @hongkai-dai)

___
*[`geometry/optimization/cartesian_product.cc` line 202 at r1](https://reviewable.io/reviews/hongkai-dai/drake/31#-NYUD9GP8mNFLySKXRLy:-NYUDtf7EegaQR4fMrMu:bzc33tn) ([raw file](https://github.com/hongkai-dai/drake/blob/a7869fefd9e1726b8052a88347d0a5a64cd80544/geometry/optimization/cartesian_product.cc#L202)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW, For my own education, would return-value-optimization automatically move these?
</blockquote></details>

It would RVO the `std::pair` object, but RVO does not apply to the `std::pair` *arguments*, so they were being copied.

The spelling that would use NRVO without copying (e.g., to avoid `std::move` boilerplate) would look like this:

```c++
Foo::DoAddPointInSetConstraints(
    MathematicalProgram* prog,
    const Eigen::Ref<const VectorXDecisionVariable>& x) const {
  std::pair<VectorX<Variable>, std::vector<Binding<Constraint>>> ret;
  VectorX<Variable>& new_vars = ret.first;
  std::vector<Binding<Constraint>>& new_constraints = ret.second;

  // ... update new_vars and new_constraints ... as we change `prog` ...

  return ret;
}
```

That boilerplate seemed worse to me than the `std::move` boilerplate.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/drake/31)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`geometry/optimization/cartesian_product.cc` line 202 at r1](https://reviewable.io/reviews/hongkai-dai/drake/31#-NYUD9GP8mNFLySKXRLy:-NYUFngS6gWZ9KnzNn6K:bir6smh) ([raw file](https://github.com/hongkai-dai/drake/blob/a7869fefd9e1726b8052a88347d0a5a64cd80544/geometry/optimization/cartesian_product.cc#L202)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It would RVO the `std::pair` object, but RVO does not apply to the `std::pair` *arguments*, so they were being copied.

The spelling that would use NRVO without copying (e.g., to avoid `std::move` boilerplate) would look like this:

```c++
Foo::DoAddPointInSetConstraints(
    MathematicalProgram* prog,
    const Eigen::Ref<const VectorXDecisionVariable>& x) const {
  std::pair<VectorX<Variable>, std::vector<Binding<Constraint>>> ret;
  VectorX<Variable>& new_vars = ret.first;
  std::vector<Binding<Constraint>>& new_constraints = ret.second;

  // ... update new_vars and new_constraints ... as we change `prog` ...

  return ret;
}
```

That boilerplate seemed worse to me than the `std::move` boilerplate.
</blockquote></details>

I see, thanks Jeremy! I was trying to use create that `ret` object in the first place to avoid the copy. I agree now the code looks better.

**Review by hongkai-dai — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hongkai-dai/drake/31)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jwnimmer-tri)

**Pull request merged**
